apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: orchestrator-metrics
  namespace: observability
  labels:
    app: orchestrator
    release: prometheus
spec:
  selector:
    matchLabels:
      app: orchestrator
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - somaagent
      - soma-agent-hub
      - soma-memory
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gateway-metrics
  namespace: observability
  labels:
    app: gateway-api
    release: prometheus
spec:
  selector:
    matchLabels:
      app: gateway-api
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - somaagent
      - soma-agent-hub
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: policy-engine-metrics
  namespace: observability
  labels:
    app: policy-engine
    release: prometheus
spec:
  selector:
    matchLabels:
      app: policy-engine
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - somaagent
      - soma-agent-hub
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: identity-service-metrics
  namespace: observability
  labels:
    app: identity-service
    release: prometheus
spec:
  selector:
    matchLabels:
      app: identity-service
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - somaagent
      - soma-agent-hub
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: somallm-provider-metrics
  namespace: observability
  labels:
    app: somallm-provider
    release: prometheus
spec:
  selector:
    matchLabels:
      app: somallm-provider
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - somaagent
      - soma-agent-hub
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: all-somaagent-services
  namespace: observability
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      monitoring: enabled
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - somaagent
      - soma-agent-hub
      - soma-memory
