auth_enabled: false

ingester:
  chunk_idle_period: 3m
  max_chunk_age: 5m
  max_streams_per_user: 10000

schema_config:
  configs:
    - from: 2024-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

common:
  path_prefix: /loki
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  ingestion_rate_mb: 256
  ingestion_burst_size_mb: 512

query_scheduler:
  max_cache_freshness_per_query: 10m

server:
  http_listen_port: 3100
  log_level: info
