{{- $namespace := .Values.global.namespace | default .Release.Namespace -}}
{{- range $name, $svc := .Values.services }}
{{- if $svc.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
  labels:
    app: {{ $name }}
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/part-of: {{ $.Chart.Name }}
spec:
  replicas: {{ $svc.replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
        app.kubernetes.io/name: {{ $name }}
        app.kubernetes.io/part-of: {{ $.Chart.Name }}
    spec:
      containers:
        - name: {{ $name }}
          image: {{- $img := (printf "%v" $svc.image) -}}{{- if or (hasSuffix ":latest" $img) (hasSuffix ":dev" $img) (hasSuffix ":prod" $img) (hasSuffix ":stable" $img) (contains ":" $img) -}}
            {{ $img }}
            {{- else -}}
            {{ $img }}:{{ $.Values.global.imageTag | default "latest" }}
            {{- end }}
          imagePullPolicy: {{ $svc.imagePullPolicy | default $.Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ $svc.port }}
          {{- if $svc.env }}
          env:
          {{- range $env := $svc.env }}
            - name: {{ $env.name }}
              value: {{ $env.value | quote }}
          {{- end }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ $svc.port }}
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: {{ $svc.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
{{- if $svc.resources }}
          resources:
            limits:
{{ toYaml $svc.resources.limits | indent 14 }}
            requests:
{{ toYaml $svc.resources.requests | indent 14 }}
{{- end }}
{{- end }}
{{- end }}