{{- if .Values.mtls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mtls.secretName }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.mtls.secretName }}
    app.kubernetes.io/part-of: {{ $.Chart.Name }}
type: Opaque
data:
  tls.crt: {{ .Values.mtls.tlsCrt | b64enc | quote }}
  tls.key: {{ .Values.mtls.tlsKey | b64enc | quote }}
{{- end }}