{{- $namespace := .Values.global.namespace | default .Release.Namespace -}}
{{- range $name, $svc := .Values.services }}
{{- if and $svc.enabled $svc.pdb $svc.pdb.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/part-of: {{ $.Chart.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}
  {{- if $svc.pdb.maxUnavailable }}
  maxUnavailable: {{ $svc.pdb.maxUnavailable }}
  {{- else if $svc.pdb.minAvailable }}
  minAvailable: {{ $svc.pdb.minAvailable }}
  {{- else }}
  minAvailable: 1
  {{- end }}
{{- end }}
{{- end }}
