{{- if .Values.qdrant.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: qdrant
  labels:
    app: qdrant
spec:
  ports:
    - name: http
      port: {{ .Values.ports.qdrant }}
      targetPort: 6333
  selector:
    app: qdrant
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qdrant
  labels:
    app: qdrant
spec:
  serviceName: qdrant
  replicas: {{ .Values.qdrant.replicaCount }}
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      containers:
        - name: qdrant
          image: {{ .Values.qdrant.image }}
          imagePullPolicy: {{ $.Values.global.imagePullPolicy }}
          ports:
            - containerPort: 6333
          volumeMounts:
            - name: data
              mountPath: /qdrant/storage
          resources:
            {{- toYaml $.Values.global.resources | nindent 12 }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.qdrant.persistence.size }}
{{- end }}