version: "3.9"

services:
  zookeeper:
    image: bitnami/zookeeper:3.9
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"
    networks:
      - somaagenthub-network

  kafka:
    image: bitnami/kafka:3.7
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_INTERNAL://:29092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9093,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "false"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports:
      - "9093:9093"
    depends_on:
      - zookeeper
    networks:
      - somaagenthub-network

  kafka-init-topics:
    image: bitnami/kafka:3.7
    depends_on:
      - kafka
    entrypoint: ["/bin/bash", "-c"]
    command: >-
      "kafka-topics.sh --bootstrap-server kafka:29092 --create --if-not-exists --topic soma.events --replication-factor 1 --partitions 3 &&
       kafka-topics.sh --bootstrap-server kafka:29092 --describe --topic soma.events"
    networks:
      - somaagenthub-network
    restart: "on-failure"

  pushgateway:
    image: prom/pushgateway:v1.8.0
    ports:
      - "9091:9091"
    networks:
      - somaagenthub-network

  flink-jobmanager:
    image: somagent/flink-service:dev
    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: flink-jobmanager
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      KAFKA_TOPIC: soma.events
      PROMETHEUS_PUSHGATEWAY: http://pushgateway:9091
      PROMETHEUS_JOB_NAME: soma_flink_job
    entrypoint: ["/docker-entrypoint.sh", "jobmanager"]
    ports:
      - "8082:8081"
    depends_on:
      - kafka-init-topics
      - pushgateway
    networks:
      - somaagenthub-network

  flink-taskmanager:
    image: somagent/flink-service:dev
    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: flink-jobmanager
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      KAFKA_TOPIC: soma.events
      PROMETHEUS_PUSHGATEWAY: http://pushgateway:9091
      PROMETHEUS_JOB_NAME: soma_flink_job
    entrypoint: ["/docker-entrypoint.sh", "taskmanager"]
    depends_on:
      - flink-jobmanager
    networks:
      - somaagenthub-network

  flink-job-submitter:
    image: somagent/flink-service:dev
    depends_on:
      - flink-jobmanager
    entrypoint: ["flink", "run", "--jobmanager", "flink-jobmanager:8081", "-py", "/opt/flink/job.py"]
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      KAFKA_TOPIC: soma.events
      PROMETHEUS_PUSHGATEWAY: http://pushgateway:9091
      PROMETHEUS_JOB_NAME: soma_flink_job
    networks:
      - somaagenthub-network
    restart: "on-failure"

networks:
  somaagenthub-network:
    external: true
