# Dev profile for soma-infra (singletons, no persistence)
namespace: soma-infra

kafka:
  enabled: true
  replicaCount: 1
  kraft:
    enabled: true
  persistence:
    enabled: false
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 400m
      memory: 512Mi

redis:
  enabled: true
  architecture: standalone
  master:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
  replica:
    replicaCount: 0
  auth:
    enabled: false
  persistence:
    enabled: false

prometheus:
  enabled: false

grafana:
  enabled: false

opa:
  enabled: false

vault:
  enabled: false

etcd:
  enabled: false
