# Default values for soma-agent-hub Helm chart.
# These values are used to render the templates under templates/.

# Global settings
global:
  imagePullPolicy: IfNotPresent
  namespace: soma-agent-hub
  imageTag: "dev"
  securityContext:
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop: ["ALL"]
  environment: production
  observability:
    enableOtlp: true
    otlpEndpoint: "http://otel-collector.observability:4317"
  spiffe:
    enabled: true
    trustDomain: "somaagent.io"
    certDir: "/var/run/secrets/spiffe"
    socketPath: "/run/spire/sockets/agent.sock"
    socketMountPath: "/run/spire/sockets"
    hostSocketPath: "/run/spire/sockets"

# Centralized port definitions. This is the single source of truth for all service ports.
ports:
  gateway-api: 10000
  orchestrator: 10001
  identity-service: 10002
  policy-engine: 10003
  memory-gateway: 10004
  slm-service: 10005
  tool-service: 10006
  analytics-service: 10007
  settings-service: 10008
  billing-service: 10009
  constitution-service: 10010
  task-capsule-repo: 10011
  jobs: 10012
  # Ensure all services have a port defined, even if disabled by default
  "self-provisioning": 10013
  "evolution-engine": 10014
  "marketplace-service": 10015
  "voice-interface": 10016
  "recall-service": 10017
  "notification-service": 10018
  "model-proxy": 10019
  "capsule-service": 10020
  "kamachiq-service": 10021
  "mao-service": 10022
  "token-estimator": 10023
  "flink-service": 10024
  "airflow-service": 10025

# Centralized secrets configuration
secrets:
  enabled: true
  name: soma-secrets
  generateDevSecrets: true
  identityJwt: ""
  gatewayJwt: ""

# Kafka (Bitnami) configuration – KRaft mode
defaultKafka:
  enabled: true
  replicaCount: 3
  kraft:
    enabled: true
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "250m"
      memory: "256Mi"

# Service definitions – each microservice can override these defaults
services:
  jobs:
    enabled: false
  slm-service:
    enabled: true
    replicaCount: 1
    image: "somaagent/soma-slm-service"
  policy-engine:
    enabled: true
    image: "somaagent/soma-policy-engine"
  memory-gateway:
    enabled: false
  orchestrator:
    enabled: true
    image: "somaagent/soma-orchestrator"
    env:
      - name: TEMPORAL_ENABLED
        value: "false"
    serviceAccount:
      create: true
      name: orchestrator
    volcano:
      enabled: false
      defaultQueue: interactive
      sessionImage: python:3.11-slim
      sessionCpu: 500m
      sessionMemory: 512Mi
      jobTimeoutSeconds: 300
  settings-service:
    enabled: false
  task-capsule-repo:
    enabled: false
  gateway-api:
    enabled: true
    replicaCount: 1
    image: "somaagent/soma-gateway-api"
    envFromSecret: "soma-secrets"
  identity-service:
    enabled: true
    image: "somaagent/soma-identity-service"
    envFromSecret: "soma-secrets"
    env:
      - name: REDIS_URL
        value: ""
  constitution-service:
    enabled: false
  analytics-service:
    enabled: false
  billing-service:
    enabled: false

# Ingress configuration
ingress:
  enabled: false
  # other ingress fields left unchanged but will be ignored when disabled

monitoring:
  serviceMonitors:
    enabled: false
    namespace: observability
    interval: 30s
