# Default values for soma-agent-hub Helm chart.
# These values are used to render the templates under templates/.

# Global settings
global:
  imagePullPolicy: IfNotPresent
  namespace: soma-agent-hub   # renamed from soma-agent-hub
  imageTag: "latest"

# Default hub port for gateway-api (used in service definition)
hubPort: 60000

# Kafka (Bitnami) configuration – KRaft mode
defaultKafka:
  enabled: true
  replicaCount: 3
  ## Enable KRaft (no Zookeeper)
  kraft:
    enabled: true
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "250m"
      memory: "256Mi"

# Kafka KRaft configuration - disabled for local development
kafka:
  enabled: false
  replicaCount: 3
  kraft:
    enabled: true
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "250m"
      memory: "256Mi"
  persistence:
    enabled: false

# Service definitions – each microservice can override these defaults
services:
  jobs:
    enabled: false
  slm-service:
    enabled: true
    replicaCount: 1
    image: "somaagent/soma-slm-service:latest"
    imagePullPolicy: IfNotPresent
    port: 1001
  policy-engine:
    enabled: false
  memory-gateway:
    enabled: false
  orchestrator:
    enabled: false
  settings-service:
    enabled: false
  task-capsule-repo:
    enabled: false
  gateway-api:
    enabled: true
    replicaCount: 1
    image: "somaagent/soma-gateway-api:latest"
    imagePullPolicy: IfNotPresent
    port: 8080
    nodePort: 30080
  identity-service:
    enabled: false
  constitution-service:
    enabled: false
  analytics-service:
    enabled: false
  billing-service:
    enabled: false

# Ingress configuration
ingress:
  enabled: false
  # other ingress fields left unchanged but will be ignored when disabled

monitoring:
  serviceMonitors:
    enabled: false
    namespace: observability
    interval: 30s
