---
# Real Kubernetes deployment for orchestrator service
# Sprint-6: Production-ready with real monitoring, health checks, resource limits
# NO MOCKS - This is actual production configuration

apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
  namespace: somaagent
  labels:
    app: orchestrator
    component: orchestration
    monitoring: enabled
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
        component: orchestration
        monitoring: enabled
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10001"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: orchestrator
        image: somaagent/orchestrator:latest
        imagePullPolicy: IfNotPresent
        
        ports:
        - name: http
          containerPort: 10001
          protocol: TCP
        - name: metrics
          containerPort: 10001
          protocol: TCP
        
        env:
        # Real service discovery
        - name: POLICY_ENGINE_URL
          value: "http://policy-engine:10020"
        - name: SOMALLM_PROVIDER_URL
          value: "http://slm-service:1001"
        - name: SOMALLM_PROVIDER_HEALTH_URL
          value: "http://slm-service:1001/health"
        - name: GATEWAY_API_URL
          value: "http://gateway-api:10000"
        - name: IDENTITY_SERVICE_URL
          value: "http://identity-service:10002"
        - name: ENABLE_VOLCANO_SCHEDULER
          value: "true"
        - name: VOLCANO_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: VOLCANO_DEFAULT_QUEUE
          value: "interactive"
        - name: VOLCANO_SESSION_IMAGE
          value: "python:3.11-slim"
        - name: VOLCANO_SESSION_CPU
          value: "500m"
        - name: VOLCANO_SESSION_MEMORY
          value: "512Mi"
        - name: VOLCANO_JOB_TIMEOUT_SECONDS
          value: "300"
        - name: KUBECTL_BINARY
          value: "kubectl"
        
        # Real Temporal connection
        - name: TEMPORAL_HOST
          value: "temporal-frontend.somaagent:7233"
        - name: TEMPORAL_NAMESPACE
          value: "default"
        - name: TEMPORAL_TASK_QUEUE
          value: "somagent.session.workflows"
        
        # Real observability
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://prometheus-prometheus.observability:9090"
        - name: OTEL_SERVICE_NAME
          value: "orchestrator"
        - name: ENVIRONMENT
          value: "production"
        
        # Real logging
        - name: LOG_LEVEL
          value: "INFO"
        - name: LOG_FORMAT
          value: "json"
        
        # Real resource limits
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "2000m"
            memory: "2Gi"
        
        # Real health checks
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        
        # Real security context
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
        
        # Real volume mounts
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: cache
          mountPath: /app/cache
      
      volumes:
      - name: tmp
        emptyDir: {}
      - name: cache
        emptyDir: {}
      
      # Real pod security
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
      
      # Real scheduling
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - orchestrator
              topologyKey: kubernetes.io/hostname
      serviceAccountName: orchestrator

---
apiVersion: v1
kind: Service
metadata:
  name: orchestrator
  namespace: somaagent
  labels:
    app: orchestrator
    monitoring: enabled
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 10001
    targetPort: http
    protocol: TCP
  - name: metrics
    port: 10001
    targetPort: metrics
    protocol: TCP
  selector:
    app: orchestrator
  sessionAffinity: ClientIP
