---
# Real Kubernetes deployment for policy-engine
# Sprint-6: Production policy enforcement with real constitution

apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-engine
  namespace: somaagent
  labels:
    app: policy-engine
    component: policy
    monitoring: enabled
spec:
  replicas: 2
  selector:
    matchLabels:
      app: policy-engine
  template:
    metadata:
      labels:
        app: policy-engine
        component: policy
        monitoring: enabled
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8001"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: policy-engine
        image: somaagent/policy-engine:latest
        imagePullPolicy: IfNotPresent
        
        ports:
        - name: http
          containerPort: 8001
          protocol: TCP
        - name: metrics
          containerPort: 8100
          protocol: TCP
        
        env:
        # Real Redis connection
        - name: REDIS_HOST
          value: "redis.somaagent"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_DB
          value: "0"
        
        # Real constitution service
        - name: CONSTITUTION_SERVICE_URL
          value: "http://constitution-service:8004"
        
        # Real observability
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://prometheus-prometheus.observability:9090"
        - name: OTEL_SERVICE_NAME
          value: "policy-engine"
        - name: ENVIRONMENT
          value: "production"
        
        # Real policy settings
        - name: CACHE_TTL_SECONDS
          value: "300"
        - name: MAX_VIOLATIONS_BEFORE_BLOCK
          value: "3"
        
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "2000m"
            memory: "2Gi"
        
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL

---
apiVersion: v1
kind: Service
metadata:
  name: policy-engine
  namespace: somaagent
  labels:
    app: policy-engine
    monitoring: enabled
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8001
    targetPort: http
    protocol: TCP
  - name: metrics
    port: 8100
    targetPort: metrics
    protocol: TCP
  selector:
    app: policy-engine
