---
# Real Kubernetes deployment for SomaLLM provider (renamed)
# Updated ports to 1001

apiVersion: apps/v1
kind: Deployment
metadata:
  name: somallm-provider
  namespace: somaagent
  labels:
    app: somallm-provider
    component: inference
    monitoring: enabled
spec:
  replicas: 2
  selector:
    matchLabels:
      app: somallm-provider
  template:
    metadata:
      labels:
        app: somallm-provider
        component: inference
        monitoring: enabled
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "1001"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: somallm-provider
        image: somaagent/somallm-provider:latest
        imagePullPolicy: IfNotPresent
        
        ports:
        - name: http
          containerPort: 1001
          protocol: TCP
        - name: metrics
          containerPort: 1002
          protocol: TCP
        
        env:
        - name: MODEL_PATH
          value: "/models"
        - name: DEFAULT_MODEL
          value: "llama-3.2-1b"
        - name: MAX_CONCURRENT_REQUESTS
          value: "10"
        - name: CUDA_VISIBLE_DEVICES
          value: "0"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://prometheus-prometheus.observability:9090"
        - name: OTEL_SERVICE_NAME
          value: "somallm-provider"
        - name: ENVIRONMENT
          value: "production"
        
        resources:
          requests:
            cpu: "2000m"
            memory: "4Gi"
          limits:
            cpu: "8000m"
            memory: "16Gi"
        
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
        
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
        
        volumeMounts:
        - name: models
          mountPath: /models
          readOnly: true
        - name: cache
          mountPath: /app/cache
      
      volumes:
      - name: models
        persistentVolumeClaim:
          claimName: somallm-provider-models
      - name: cache
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: somallm-provider
  namespace: somaagent
  labels:
    app: somallm-provider
    monitoring: enabled
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 1001
    targetPort: http
    protocol: TCP
  - name: metrics
    port: 1002
    targetPort: metrics
    protocol: TCP
  selector:
    app: somallm-provider
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: somallm-provider-models
  namespace: somaagent
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard
