#!/bin/bash
# deploy-unified.sh
# Unified deployment script for SomaAgentHub
# Deploys the consolidated architecture

set -e  # Exit on any error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
PROJECT_NAME="somaagenthub-unified"
COMPOSE_FILE="docker-compose-unified.yml"
ENV_FILE=".env"

# Logging functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check prerequisites
check_prerequisites() {
    log_info "Checking prerequisites..."
    
    # Check Docker
    if ! command -v docker &> /dev/null; then
        log_error "Docker is not installed. Please install Docker first."
        exit 1
    fi
    
    # Check Docker Compose
    if ! command -v docker-compose &> /dev/null && ! docker compose version &> /dev/null; then
        log_error "Docker Compose is not installed. Please install Docker Compose first."
        exit 1
    fi
    
    # Check if compose file exists
    if [[ ! -f "$COMPOSE_FILE" ]]; then
        log_error "Docker Compose file not found: $COMPOSE_FILE"
        exit 1
    fi
    
    log_success "Prerequisites check passed"
}

# Create .env file if it doesn't exist
setup_environment() {
    log_info "Setting up environment..."
    
    if [[ ! -f "$ENV_FILE" ]]; then
        log_info "Creating .env file with default values..."
        cat > "$ENV_FILE" << EOF
# SomaAgentHub Unified Configuration
# Generated by deploy-unified.sh

# Port Configuration
MAO_ENGINE_PORT=10000
DATA_LAYER_PORT=10001
AI_SERVICES_PORT=10002
GOVERNANCE_PORT=10003

# Database Configuration
POSTGRES_USER=soma
POSTGRES_PASSWORD=soma
POSTGRES_DB=soma
POSTGRES_PORT=15432

# ClickHouse Configuration
CLICKHOUSE_USER=soma
CLICKHOUSE_PASSWORD=soma
CLICKHOUSE_DB=soma_analytics
CLICKHOUSE_PORT=19000
CLICKHOUSE_HTTP_PORT=18123

# Redis Configuration
REDIS_PORT=16379

# Temporal Configuration
TEMPORAL_NAMESPACE=default
TEMPORAL_UI_PORT=18023
TEMPORAL_WEB_PORT=18024
TEMPORAL_UI_WEB_PORT=18080

# Observability Configuration
PROMETHEUS_PORT=19090


# Governance Configuration
JWT_SECRET=your-secret-key-change-this-in-production

# Debug Configuration
MAO_ENGINE_DEBUG=false
DATA_LAYER_DEBUG=false
AI_SERVICES_DEBUG=false
GOVERNANCE_DEBUG=false
EOF
        log_success "Created .env file with default values"
        log_warning "Please review and update .env file for production use"
    else
        log_info "Using existing .env file"
    fi
}

# Create monitoring configuration
setup_monitoring() {
    log_info "Setting up monitoring configuration..."
    
    # Create monitoring directory
    mkdir -p monitoring
    
    # Create Prometheus configuration
    cat > monitoring/prometheus.yml << EOF
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mao-engine'
    static_configs:
      - targets: ['mao-engine:8000']

  - job_name: 'data-layer'
    static_configs:
      - targets: ['data-layer:8001']

  - job_name: 'ai-services'
    static_configs:
      - targets: ['ai-services:8002']

  - job_name: 'governance'
    static_configs:
      - targets: ['governance:8003']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'clickhouse'
    static_configs:
      - targets: ['clickhouse:9123']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
EOF

log_success "Monitoring configuration created"
}

# Build services
build_services() {
    log_info "Building services..."
    
    # Build using docker compose
    if command -v docker-compose &> /dev/null; then
        docker-compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" build --no-cache
    else
        docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" build --no-cache
    fi
    
    log_success "Services built successfully"
}

# Start services
start_services() {
    log_info "Starting services..."
    
    # Start services using docker compose
    if command -v docker-compose &> /dev/null; then
        docker-compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" up -d
    else
        docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" up -d
    fi
    
    log_success "Services started successfully"
}

# Wait for services to be healthy
wait_for_services() {
    log_info "Waiting for services to be healthy..."
    
    # Wait for core services
    services=("mao-engine" "data-layer" "ai-services" "governance")
    
    for service in "${services[@]}"; do
        log_info "Waiting for $service to be healthy..."
        
        # Wait up to 5 minutes for each service
        timeout=300
        elapsed=0
        
        while [[ $elapsed -lt $timeout ]]; do
            # Check service health
            if command -v docker-compose &> /dev/null; then
                status=$(docker-compose -f "$COMPOSE_FILE" ps -q "$service" | xargs docker inspect --format='{{.State.Health.Status}}' 2>/dev/null || echo "starting")
            else
                status=$(docker compose -f "$COMPOSE_FILE" ps -q "$service" | xargs docker inspect --format='{{.State.Health.Status}}' 2>/dev/null || echo "starting")
            fi
            
            if [[ "$status" == "healthy" ]]; then
                log_success "$service is healthy"
                break
            fi
            
            sleep 5
            elapsed=$((elapsed + 5))
            
            if [[ $elapsed -ge $timeout ]]; then
                log_error "$service did not become healthy within $timeout seconds"
                exit 1
            fi
        done
    done
    
    log_success "All services are healthy"
}

# Show service status
show_status() {
    log_info "Service status:"
    
    if command -v docker-compose &> /dev/null; then
        docker-compose -f "$COMPOSE_FILE" ps
    else
        docker compose -f "$COMPOSE_FILE" ps
    fi
}

# Show access URLs
show_access_urls() {
    log_info "Access URLs:"
    
    # Read ports from .env file
    source "$ENV_FILE"
    
    echo -e "${GREEN}MAO Engine:${NC}          http://localhost:${MAO_ENGINE_PORT:-10000}"
    echo -e "${GREEN}Data Layer:${NC}          http://localhost:${DATA_LAYER_PORT:-10001}"
    echo -e "${GREEN}AI Services:${NC}         http://localhost:${AI_SERVICES_PORT:-10002}"
    echo -e "${GREEN}Governance:${NC}          http://localhost:${GOVERNANCE_PORT:-10003}"
    echo -e "${GREEN}Temporal UI:${NC}         http://localhost:${TEMPORAL_UI_WEB_PORT:-18080}"
    
    echo -e "${GREEN}Prometheus:${NC}          http://localhost:${PROMETHEUS_PORT:-19090}"
    echo -e "${GREEN}ClickHouse HTTP:${NC}     http://localhost:${CLICKHOUSE_HTTP_PORT:-18123}"
}

# Main deployment function
deploy() {
    log_info "Starting unified SomaAgentHub deployment..."
    
    check_prerequisites
    setup_environment
    setup_monitoring
    build_services
    start_services
    wait_for_services
    show_status
    show_access_urls
    
    log_success "Unified SomaAgentHub deployment completed successfully!"
    log_info "To view logs: docker-compose -f $COMPOSE_FILE logs -f"
    log_info "To stop services: docker-compose -f $COMPOSE_FILE down"
}

# Handle command line arguments
case "${1:-deploy}" in
    deploy)
        deploy
        ;;
    build)
        check_prerequisites
        setup_environment
        build_services
        ;;
    start)
        check_prerequisites
        setup_environment
        start_services
        ;;
    stop)
        log_info "Stopping services..."
        if command -v docker-compose &> /dev/null; then
            docker-compose -f "$COMPOSE_FILE" down
        else
            docker compose -f "$COMPOSE_FILE" down
        fi
        log_success "Services stopped"
        ;;
    restart)
        log_info "Restarting services..."
        stop
        start
        ;;
    status)
        show_status
        ;;
    logs)
        log_info "Showing logs..."
        if command -v docker-compose &> /dev/null; then
            docker-compose -f "$COMPOSE_FILE" logs -f "${2:-}"
        else
            docker compose -f "$COMPOSE_FILE" logs -f "${2:-}"
        fi
        ;;
    clean)
        log_warning "This will remove all containers, networks, and volumes!"
        read -p "Are you sure? (y/N): " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            log_info "Cleaning up..."
            if command -v docker-compose &> /dev/null; then
                docker-compose -f "$COMPOSE_FILE" down -v --rmi all
            else
                docker compose -f "$COMPOSE_FILE" down -v --rmi all
            fi
            log_success "Cleanup completed"
        fi
        ;;
    help|--help|-h)
        echo "SomaAgentHub Unified Deployment Script"
        echo ""
        echo "Usage: $0 [command]"
        echo ""
        echo "Commands:"
        echo "  deploy    - Full deployment (default)"
        echo "  build     - Build services only"
        echo "  start     - Start services only"
        echo "  stop      - Stop services"
        echo "  restart   - Restart services"
        echo "  status    - Show service status"
        echo "  logs      - Show logs (optional: service name)"
        echo "  clean     - Remove all containers, networks, and volumes"
        echo "  help      - Show this help message"
        ;;
    *)
        log_error "Unknown command: $1"
        echo "Use '$0 help' to see available commands"
        exit 1
        ;;
esac