apiVersion: v1
kind: Service
metadata:
  name: {{APP_NAME}}
  labels:
    app: {{APP_NAME}}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: {{APP_NAME}}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
