apiVersion: v1
kind: Namespace
metadata:
  name: temporal
  labels:
    name: temporal
    environment: production
    app.kubernetes.io/name: temporal
    app.kubernetes.io/component: workflow-engine
