apiVersion: v1
kind: Service
metadata:
  name: temporal-frontend
  namespace: temporal
  labels:
    app: temporal-server
    component: frontend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
spec:
  type: LoadBalancer
  ports:
  - name: grpc
    port: 7233
    targetPort: 7233
    protocol: TCP
  selector:
    app: temporal-server
  sessionAffinity: ClientIP

---
apiVersion: v1
kind: Service
metadata:
  name: temporal-ui
  namespace: temporal
  labels:
    app: temporal-ui
    component: web-ui
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: temporal-ui
  sessionAffinity: ClientIP

---
apiVersion: v1
kind: Service
metadata:
  name: temporal-metrics
  namespace: temporal
  labels:
    app: temporal-server
    component: metrics
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  selector:
    app: temporal-server
