name: CI - Orchestrator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    name: Run Python unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f services/orchestrator/requirements.txt ]; then
            pip install -r services/orchestrator/requirements.txt
          fi

      - name: Run orchestrator tests
        working-directory: .
        run: |
          pytest services/orchestrator/tests -q

  volcano-smoke:
    name: "Volcano integration smoke (optional)"
    # This job is intended to run on a self-hosted runner that has Docker/Kind/Helm installed.
    # To enable it, set the repository secret RUN_VOLCANO_SMOKE=true and target a self-hosted runner.
    runs-on: [self-hosted, linux]
    if: ${{ secrets.RUN_VOLCANO_SMOKE == 'true' }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Ensure tools
        run: |
          # Assumes self-hosted runner has kind/helm/kubectl installed; verify versions
          kind --version || true
          kubectl version --client || true
          helm version || true

      - name: Run integration smoke script
        run: |
          chmod +x scripts/volcano/run-integration-smoke.sh
          scripts/volcano/run-integration-smoke.sh

      - name: Run Volcano integration tests
        env:
          VOLCANO_INTEGRATION_ENABLED: "1"
          VOLCANO_NAMESPACE: "soma-agent-hub"
        run: |
          pytest tests/integration/volcano -q
