name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: soma
          POSTGRES_PASSWORD: soma_pass
          POSTGRES_DB: soma
        ports: ["5432:5432"]
        options: >-
          --health-cmd "pg_isready -U $POSTGRES_USER"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:7-alpine
        ports: ["6379:6379"]
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install all service requirements (each service has its own file)
          find services -name requirements.txt -exec cat {} + > combined-requirements.txt
          pip install -r combined-requirements.txt
          pip install -r requirements-dev.txt
      - name: Lint with ruff
        run: ruff check .
      - name: Type check with mypy
        run: mypy .
      - name: Run tests
        env:
          POSTGRES_URL: postgresql://soma:soma_pass@localhost:5432/soma
          REDIS_URL: redis://localhost:6379/0
        run: pytest
      
      - name: Build Docker Images (on main branch)
        if: github.ref == 'refs/heads/main'
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          ./scripts/build_and_push.sh ghcr.io/somatechlat ${{ github.sha }}
      
      - name: Setup Kind cluster for integration testing
        uses: helm/kind-action@v1
        with:
          cluster_name: soma-test
      
      - name: Deploy and test Helm chart
        run: |
          helm dependency update ./k8s/helm/soma-agent
          helm install soma-agent ./k8s/helm/soma-agent --namespace soma-agent --create-namespace --wait --timeout=300s
          kubectl wait --for=condition=Ready pod -l app.kubernetes.io/part-of=soma-agent -n soma-agent --timeout=300s || true
          helm test soma-agent --namespace soma-agent || echo "Helm tests not yet implemented"
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - name: Add Bitnami repo for Kafka
        run: helm repo add bitnami https://charts.bitnami.com/bitnami && helm repo update
      - name: Update Helm dependencies
        working-directory: ./k8s/helm/soma-agent
        run: helm dependency update .
      - name: Lint Helm chart
        working-directory: ./k8s/helm/soma-agent
        run: helm lint .
      - name: Render Helm templates (validate)
        working-directory: ./k8s/helm/soma-agent
        run: helm template soma-agent . > /dev/null
