name: CI

on:
  pull_request:
  push:
    branches: [ main, develop, chore/**, feat/**, fix/** ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dev requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Lint (ruff)
        run: |
          ruff --version
          ruff check --output-format=github .

      - name: Type check (mypy)
        run: |
          mypy --version
          mypy services || true

      - name: Set up Helm
        uses: azure/setup-helm@v4
      - name: Helm lint
        run: |
          helm lint ./k8s/helm/soma-agent || true
          helm template soma-agent-hub ./k8s/helm/soma-agent > /dev/null

      - name: Run unit tests (fast subset)
        run: |
          pytest -q --maxfail=1 --disable-warnings
